//
//  StringConstants.swift
//  TradingPanel
//
//  Created by Volodymyr Babych on 18.02.2024.
//

import Foundation
struct StringConstants {
    static let kLblLimit: String = "Limit"
    static let k: String = ""
    static let kLblBtcUsdt: String = "BTC/USDT"
    static let kLbl6000: String = "60.00"
    static let kLblBuy: String = "Buy"
    static let kLbl0: String = "0%"
    static let kLblUsdt: String = "USDT"
    static let kLbl4289305: String = "=$42.893.05"
    static let kLbl43: String = "43%"
    static let kLbl25: String = "25%"
    static let kLbl00066: String = "0.0066"
    static let kLbl100: String = "100%"
    static let kLbl1800: String = "18.00 "
    static let kLbl1085045: String = "10,850.45"
    static let kMsg080911290: String = "08/09 - 11:29:05"
    static let kLblConvert: String = "Convert"
    static let kLblAmount: String = "Amount"
    static let kLbl18001800: String = "18.00 / 18.00"
    static let kLblTotal: String = "Total"
    static let kLblPriceUsdt: String = "Price(USDT)"
    static let kLbl01: String = "0.1"
    static let kHttpFail: String = "HTTP request failed"
    static let kLbl4289799: String = "42.897.99"
    static let kLblQuantityArb: String = "Quantity(ARB)"
    static let kLbl75: String = "75%"
    static let kLblCancelAll: String = "Cancel All"
    static let kLblSell: String = "Sell"
    static let kLbl50: String = "50%"
    static let kLblFunds: String = "Funds"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLbl121Usd: String = "=1.21 USD"
    static let kLbl244: String = "+2,44%"
    static let kLbl000: String = "0.00"
    static let kLblPrice: String = "Price"
    static let kLblBtc: String = "BTC"
    static let kLblCancel: String = "Cancel"
    static let kLblSpot: String = "Spot"
    static let kLbl427191: String = "42,719,1"
    static let kLblLimitSell: String = "Limit/Sell"
    static let kLbl18002: String = "/ 18.00"
    static let kLblOrderHistory: String = "Order History"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblMargin: String = "Margin"
    static let kLblMaxBuy: String = "Max. Buy"
    static let kLblOpenOrder1: String = "Open Order(1)"
    static let kLblMacd: String = "MACD"
    static let kLbl24hHigh: String = "24h High"
    static let kLblRsi: String = "RSI"
    static let kLbl4378718: String = "43.787,18"
    static let kLbl4242109: String = "42.421,09"
    static let kLblLine: String = "Line"
    static let kLblEma: String = "EMA"
    static let kLblRecentTrading: String = "Recent Trading"
    static let kLblAlert: String = "Alert"
    static let kLblInfo: String = "Info"
    static let kLblKdj: String = "KDJ"
    static let kLbl24hLow: String = "24h Low"
    static let kLbl428979: String = "42.897.9"
    static let kLbl11276m: String = "112.76M"
    static let kLbl24hAmountBtc: String = "24h Amount(BTC)"
    static let kLbl1d: String = "1d"
    static let kLblMa: String = "MA"
    static let kLbl1h: String = "1h"
    static let kLblBoll: String = "BOLL"
    static let kLblMore: String = "More"
    static let kLblQuantityBtc: String = "Quantity (BTC)"
    static let kMsg24hVolumeUsdt: String = "24h Volume(USDT)"
    static let kLblChart: String = "Chart"
    static let kLblWr: String = "WR"
    static let kLbl1w: String = "1w"
    static let kLblVol: String = "VOL"
    static let kLblOrderBook: String = "Order Book"
    static let kLbl376210: String = "3.762,10"
    static let kLbl15m: String = "15m"
    static let kLblDepth: String = "Depth"
    static let kLbl4h: String = "4h"
}
